name: CI/CD
# 触发条件为 push
on: [push] # 执行时机的
# 任务
jobs:
  test:
    # 运行的环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - uses: actions/checkout@v2 # git pull
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: 打包镜像, 上传 Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker build -t chat-ai-web-image  .
          docker tag chat-ai-web-image registry.cn-hangzhou.aliyuncs.com/pengliang/chat-ai-web
          docker push registry.cn-hangzhou.aliyuncs.com/pengliang/chat-ai-web:latest

      - name: 登录服务器, 执行脚本
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop chat-ai-web
            docker rm chat-ai-web
            docker rmi chat-ai-web:latest
            docker pull registry.cn-hangzhou.aliyuncs.com/pengliang/chat-ai-web:latest
            docker run -d -p 10012:80 --name chat-ai-web chat-ai-web:latest
